# If the shortcut to open the wrap inventory when shift & right-clicking and should be enabled
open-shortcut: true

# Settings on how permissions should be handled
permission-settings:
  # If permission checks should be performed during usage for...
  # ...physical wraps
  check-permission-physical: false
  # ...virtual wraps
  check-permission-virtual: true
  # If permissions should be checked on appliance for...
  # ...physical wraps
  permission-physical: false
  # ...virtual wraps
  permission-virtual: true

# Preview settings
preview:
  # Duration of the preview in seconds
  duration: 5
  # Rotation per tick (50ms)
  rotation: 5
  # bob interval per tick
  bob: 5
  # this value times the current sin value
  bob-height-multiplier: 0.25
  # Sneak to cancel preview settings
  sneak-cancel:
    # If the preview should be cancelled when sneaking
    enabled: true
    # If the configured message should be sent as an action bar while previewing
    action-bar: true

# The items with wraps
items:
  # Wraps of every item in the 'SWORDS' collection
  SWORDS:
    # Wrap list
    wraps:
      1:
        # The permission to virtually apply this wrap (inventory) (nullable)
        permission: 'hmcwraps.fire_sword'
        # The UUID (global identifier), has to be unique in ALL wraps!
        uuid: 'fire_sword'
        # Either custom model id or a hook to get the custom model id
        id: '1'
        # The name in the wraps inventory
        name: '<red>Fire <gray>Wrap'
        # If it should glow in the wraps inventory (nullable)
        glow: true
        # The lore in the wraps inventory (nullable)
        lore:
          - '<gray>Apply this wrap to make your sword look fire!'
        # The flags the item should have in the wraps inventory (nullable)
        flags:
          - 'HIDE_ATTRIBUTES'
        # The physical wrap to apply (nullable)
        physical:
          # The Bukkit material or a hook
          id: 'PAPER'
          # Custom model id, automatically applies if you have set a hook in the id value
          model-id: 2
          # Name displayed
          name: '<red>Fire <gray>Wrap for <red>swords'
          # If the wrap should be given to the player after they unwrap the item or re wrap it
          keep-after-unwrap: true
          # Lore displayed
          lore:
            - '<green>Apply this to an item to wrap it!'
  # Wraps for a 'DIAMOND_PICKAXE'
  DIAMOND_PICKAXE:
    wraps:
      1:
        permission: 'hmcwraps.fire_pickaxe'
        uuid: 'fire_pickaxe'
        id: '1'
        name: '<red>Fire <gray>Wrap'
        glow: true
        lore:
          - '<gray>Apply this wrap to make your pickaxe look fire!'
        flags:
          - 'HIDE_ATTRIBUTES'
        physical:
          id: 'PAPER'
          model-id: 3
          name: '<red>Fire <gray>Wrap for <blue>Diamond Pickaxe'
          keep-after-unwrap: true
          lore:
            - '<green>Apply this to an item to wrap it!'
  IRON_SWORD:
    wraps:
      1:
        permission: 'hmcwraps.silver_sword'
        uuid: 'silver_sword'
        id: '2'
        name: '<aqua>Silver <gray>Wrap'
        glow: true
        lore:
          - '<gray>Apply this wrap to make your sword look silver!'
        flags:
          - 'HIDE_ATTRIBUTES'
  IRON_PICKAXE:
    wraps:
      1:
        permission: 'hmcwraps.silver_pickaxe'
        uuid: 'silver_pickaxe'
        id: '2'
        name: '<aqua>Silver <gray>Wrap'
        glow: true
        lore:
          - '<gray>Apply this wrap to make your pickaxe look silver!'
        flags:
          - 'HIDE_ATTRIBUTES'
  IRON_AXE:
    wraps:
      1:
        permission: 'hmcwraps.silver_axe'
        uuid: 'silver_axe'
        id: '1'
        name: '<aqua>Silver <gray>Wrap'
        glow: true
        lore:
          - '<gray>Apply this wrap to make your axe look silver!'
        flags:
          - 'HIDE_ATTRIBUTES'
  IRON_SHOVEL:
    wraps:
      1:
        permission: 'hmcwraps.silver_shovel'
        uuid: 'silver_shovel'
        id: '1'
        name: '<aqua>Silver <gray>Wrap'
        glow: true
        lore:
          - '<gray>Apply this wrap to make your shovel look silver!'
        flags:
          - 'HIDE_ATTRIBUTES'
  IRON_HOE:
    wraps:
      1:
        permission: 'hmcwraps.silver_hoe'
        uuid: 'silver_hoe'
        id: '1'
        name: '<aqua>Silver <gray>Wrap'
        glow: true
        lore:
          - '<gray>Apply this wrap to make your hoe look silver!'
        flags:
          - 'HIDE_ATTRIBUTES'

collections:
  SWORDS:
    - 'NETHERITE_SWORD'
    - 'DIAMOND_SWORD'
    - 'IRON_SWORD'
    - 'STONE_SWORD'

# The unwrapper configuration
unwrapper:
  # The Bukkit material or a hook
  id: 'PAPER'
  # Name displayed
  name: '<green><bold>Unwrapper'
  # Custom model id, automatically applies if you have set a hook in the id value
  model-id: 1
  # Lore displayed
  lore:
    - '<green>Apply this to an item to unwrap it!'
    - '<gray>You may get the physical wrap back.'

# The inventory (/wraps)
inventory:
  # The title
  title: '<red><bold>Wraps'
  # Type of inventory, SCROLLING or PAGINATED
  type: 'SCROLLING'
  # How many rows the inventory should have
  rows: 6
  # The slot to set the item the player is holding to
  target-item-slot: 49
  # The set items in the inventory, every empty slot will be filled with wraps
  items:
    # Slots start from 0
    45:
      # The Bukkit material or hook
      id: 'GRAY_STAINED_GLASS_PANE'
      # The name
      name: '<gray> '
    46:
      id: 'GRAY_STAINED_GLASS_PANE'
      name: '<gray> '
    47:
      id: 'ARROW'
      name: '<green>Previous'
      # The action: Either 'SCROLL_BACK', 'SCROLL_FORTH', 'PREVIOUS_PAGE', 'NEXT_PAGE', 'UNWRAP' to unwrap the current item, 'CLOSE' to close the inventory
      action: 'SCROLL_BACK'
    48:
      id: 'GRAY_STAINED_GLASS_PANE'
      name: '<gray> '
    50:
      id: 'GRAY_STAINED_GLASS_PANE'
      name: '<gray> '
    51:
      id: 'ARROW'
      name: '<green>Next'
      action: 'SCROLL_FORTH'
    52:
      id: 'GRAY_STAINED_GLASS_PANE'
      name: '<gray> '
    53:
      id: 'RED_CONCRETE'
      name: '<red>Unwrap'
      # The lore displayed
      lore:
        - '<gray>Unwrap your current item'
      action: 'UNWRAP'